# =============================================================
# Main Snakefile — 自動讀取 config/sample.csv
# =============================================================
import csv
from pathlib import Path

SAMPLES = {}
with open("config/sample.csv") as f:
    reader = csv.reader(f)
    for row in reader:
        # 以第一個檔名前綴作為 sample 名稱
        name = Path(row[0]).stem.split("_")[0]
        SAMPLES[name] = {"r1": row[0], "r2": row[1]}



include: "rules/fastp.smk"
include: "rules/fastqc.smk"
include: "rules/multiqc.smk"

rule all:
    input:
        # Fastp 結果
        expand("results/fastp/{sample}_R1.trim.fastq.gz", sample=SAMPLES.keys()),
        expand("results/fastp/{sample}_R2.trim.fastq.gz", sample=SAMPLES.keys()),
        expand("results/fastp/{sample}_fastp.html", sample=SAMPLES.keys()),
        # FastQC 結果
        expand("results/fastqc/{sample}_R1_fastqc.html", sample=SAMPLES.keys()),
        expand("results/fastqc/{sample}_R2_fastqc.html", sample=SAMPLES.keys()),
        # MultiQC final report
        "results/multiqc/multiqc_report.html"